name: Postman tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-and-test:
    runs-on: ubuntu-latest
    steps:
      - name:
        uses: actions/checkout@v2
#1
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: jira
          reporters: cli
#2
      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
